config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index', to: 'home#index'

  resources :users do
    resources :highlights
  end

  get '/sessions/new', to: 'sessions#new', as: :new_session
  post '/sessions', to: 'sessions#create', as: :create_session
  delete '/sessions', to: 'sessions#destroy', as: :delete_session

  root 'home#index', as: :home
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user %>

  <section class='user-info'>
    <h2 id='user-name'></h2>
    <h3 id='user-title'></h3>
    <p id='user-email' class='email'></p>  
  </section>

  <section class='user-highlights'>
    <h1>Skills</h1>
    <table id='user-highlights'></table>
  </section>
  
  <section class='user-jobs'>
    <h1>Employment</h1>
    <table id='user-jobs'></table>
  </section>

<% else %>
  <h1>Biodb</h1>

  <nav>
    <%= link_to 'sign in', new_session_path %>
    <%= link_to 'sign up', new_user_path %>
  </nav>
<% end %>


<% if current_user %>
  <script>
    user = {
      id: "<%= current_user.id %>",
      name: "<%= current_user.name %>",
      title: "<%= current_user.title %>",
      email: "<%= current_user.email %>",
      highlights: <%= (current_user.highlights.nil? ? '[]' : current_user.highlights.html_safe) %>,         // TODO: see warning comment at http://stackoverflow.com/a/3758055
      jobs: <%= (current_user.jobs.nil? ? '[]' : current_user.jobs.html_safe) %>
    };
  </script>
<% end %>