config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index', to: 'home#index'

  resources :users do
    resources :highlights
  end

  get '/sessions/new', to: 'sessions#new', as: :new_session
  post '/sessions', to: 'sessions#create', as: :create_session
  delete '/sessions', to: 'sessions#destroy', as: :delete_session

  root 'home#index', as: :home
  

end

app/models/highlight.rb
class Highlight < ActiveRecord::Base

  belongs_to :user
  
  validates :content,
    presence: true
    
  validates :sort_order,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 },
    uniqueness: { scope: :user_id, message: 'highlight sort_order must be unique for each user' }
  
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  
    before_action :set_user
    before_action :set_highlight, only: [:show, :edit, :update, :destroy]

    # GET /users/1/highlights
    # GET /users/1/highlights.json
    def index
      @highlights = @user.highlights
    end

    # GET /users/1/highlights/1
    # GET /users/1/highlights/1.json
    def show
    end

    # GET /users/1/highlights/new
    def new
      @highlight = @user.highlights.new
    end

    # GET /users/1/highlights/1/edit
    def edit
    end

    # POST /users/1/highlights
    # POST /users/1/highlights.json
    def create
      @highlight = @user.highlights.new(highlight_params)

      respond_to do |format|
        if @highlight.save
          format.html { redirect_to user_highlight_path(@user, @highlight), notice: 'Highlight was successfully created.' }
          format.json { render :show, status: :created, location: @highlight }
        else
          format.html { render :new }
          format.json { render json: @highlight.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1/highlights/1
    # PATCH/PUT /users/1/highlights/1.json
    def update
      respond_to do |format|
        if @highlight.update(highlight_params)
          format.html { redirect_to user_highlight_path(@user, @highlight), notice: 'Highlight was successfully updated.' }
          format.json { render :show, status: :ok, location: @highlight }
        else
          format.html { render :edit }
          format.json { render json: @highlight.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1/highlights/1
    # DELETE /users/1/highlights/1.json
    def destroy
      @user.highlights.destroy(@highlight)
      respond_to do |format|
        format.html { redirect_to user_highlights_url(@user), notice: 'Highlight was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end
    
    def set_highlight
      @highlight = @user.highlights.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.require(:highlight).permit(:content, :sort_order)
    end

end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/views/highlights/_form.html.erb
<%= form_for([@user, @highlight]) do |f| %>
  <% if @highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highlight.errors.count, "error") %> prohibited this highlight from being saved:</h2>

      <ul>
      <% @highlight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highlights/edit.html.erb
<h1>Editing highlight</h1>

<%= render 'form' %>

<%= link_to 'Show', user_highlight_path(@user, @highlight) %> |
<%= link_to 'Back', user_highlights_path(@user) %>

app/views/highlights/index.html.erb
<h1>Listing highlights</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @highlights.each do |highlight| %>
      <tr>
        <td><%= highlight.user %></td>
        <td><%= highlight.content %></td>
        <td><%= link_to 'Show', user_highlight_path(@user, highlight) %></td>
        <td><%= link_to 'Edit', edit_user_highlight_path(@user, highlight) %></td>
        <td><%= link_to 'Destroy', user_highlight_path(@user, highlight), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highlight', new_user_highlight_path(@user) %>

app/views/highlights/new.html.erb
<h1>New highlight</h1>

<%= render 'form' %>

<%= link_to 'Back', user_highlights_path(@user) %>

app/views/highlights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @highlight.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @highlight.content %>
</p>

<%= link_to 'Edit', edit_user_highlight_path(@user, @highlight) %> |
<%= link_to 'Back', user_highlights_path(@user) %>